# Define deployment targets.
# Required keys are deploy_dir and host.
# Optional keys are tag and ssh_port
demo:
    deploy_dir: "/services/apache/vhosts/www.demo.extension.org/railsroot/"
    host: "www.demo.extension.org"
    branch: develop
    ssh_port: 24 
prod:
    deploy_dir: "/services/apache/vhosts/www.extension.org/railsroot/"
    host: "www.extension.org"
    ssh_port: 24
    branch: master
