session_token: '1234567890123456789012345678901234567890'
urlwriter_host: 'darmok.dev'
urlwriter_protocol: 'http://'
urlwriter_port: '80'

airbrake_api_key: 'notset'
app_location: 'localdev'
account_review_url: 'http://aae.dev/questions/account_review_request'
ask_two_point_oh: 'http://aae.dev'
ask_two_point_oh_form: 'http://aae.dev/ask'

# content feeds and times
epoch_time: Time.parse('1970-01-01 00:00:00 UTC')
content_feed_refresh_since: Time.parse('2005-11-01 00:00:00 UTC')
extensionorg_copwiki_host: 'cop.extension.org'
extensionorg_demowiki_host: 'cop.demo.extension.org'

# Default sites
ask_two_point_oh: 'https://ask.extension.org/'
ask_two_point_oh_form: 'https://ask.extension.org/ask'
faq_site: 'http://cop.extension.org/faq'
events_site: 'http://cop.extension.org/events'
people_site: 'http://people.extension.org/'
learn_site: 'https://learn.extension.org/'
cop_site: 'http://cop.extension.org/wiki'
collaborate_site: 'http://collaborate.extension.org/wiki/'
create_site: 'http://create.extension.org/'
about_blog: 'http://about.extension.org/'
help_wiki: 'http://docs.extension.org/wiki/'
public_site: 'http://www.extension.org'
search_site: 'http://search.extension.org'
aae_site: 'http://aae.extension.org'
campus_site: 'http://campus.extension.org/'
pdc_site: 'http://pdc.extension.org/'
data_site: 'http://data.extension.org/'


# used to push IP Address down into the models, for the email crons
default_request_ip: '127.0.0.1'
request_ip_address: '127.0.0.1'


    # cache expiry
cache_expiry: 60

# defaults for date ranges for reports
default_datefield: 'created_at'
default_dateinterval: 'withinlastmonth'
default_timezone: 'utc'

# arbitrary maximums
default_content_limit: 3
max_content_limit: 25
events_within_days: 5
# value is days
recent_feature_limit: 30

default_feed_content_limit: 50
max_feed_content_limit: 200

geoip_data_file: <%= Rails.root%>/data/GeoIP/GeoIPCity.dat

# create database
create_database: 'prod_create'
