session_token: '1234567890123456789012345678901234567890'
urlwriter_host: 'frontporch.dev'
urlwriter_protocol: 'http://'
urlwriter_port: '80'

app_location: 'localdev'

# content feeds and times
epoch_time: Time.parse('1970-01-01 00:00:00 UTC')

# Default sites
ask_two_point_oh: 'https://ask.extension.org/'
learn_site: 'https://learn.extension.org'
ask_an_expert_form_url: 'https://ask.extension.org/ask'
events_relocation_url: 'https://learn.extension.org/'
home_url: 'https://extension.org'

# used to push IP Address down into the models, for the email crons
default_request_ip: '127.0.0.1'
request_ip_address: '127.0.0.1'

# cache expiry
cache_expiry: 60

# arbitrary maximums
default_content_limit: 3
max_content_limit: 25
events_within_days: 5
# value is days
recent_feature_limit: 30

default_feed_content_limit: 50
max_feed_content_limit: 200

geoip_data_file: <%= Rails.root%>/data/GeoIP/GeoIPCity.dat

# create database
create_database: 'prod_create'
create_site: 'http://create.extension.org/'

#imageaudit database
imageaudit_database: 'prod_imageaudit'
