# === COPYRIGHT:
#  Copyright (c) 2005-2010 North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#  BSD(-compatible)
#  see LICENSE file or view at http://about.extension.org/wiki/LICENSE

class Annotation < ActiveRecord::Base
  validates_length_of :url, :within => 1..1024
  
  # href - id generated by google
  # url - URL string WITHOUT leading http://
  # added_at - date added by Google to CSE
  
end
