# === COPYRIGHT:
#  Copyright (c) 2005-2010 North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#  BSD(-compatible)
#  see LICENSE file or view at http://about.extension.org/wiki/LICENSE

require 'lib/gdata_cse'

class Annotation < ActiveRecord::Base
  validates_length_of :url, :within => 1..1024
  validates_uniqueness_of :href
  
  has_many :annotation_events, :primary_key => :url
  
  after_save :log_add
  before_destroy :log_delete

  attr_accessor :client
  
  # href - id generated by google
  # url - URL string WITHOUT leading http://
  # added_at - date added by Google to CSE
  
  def after_initialize(options = {})
    Annotation.login
  end
  
  def self.login
    if @client.nil?
      @client = GData::Client::Cse.new
      rc = @client.clientlogin(AppConfig.configtable['cse_uid'],
                            AppConfig.configtable['cse_secret'])
    end
  end
  
  def added_at=(microseconds)
    write_attribute(:added_at, Time.at(Integer(microseconds)/1000000))
  end
  
  def log_add
    self.log_event(AnnotationEvent::URL_ADDED)
  end
  
  def log_delete
    self.log_event(AnnotationEvent::URL_DELETED)
  end
 
  def log_event(action)
    AnnotationEvent.log_event(self, action)
  end
  
  def self.initial_setup
    self.login
    domains = @client.getAnnotations
    
    added = errs = 0
    
    domains.each do |annote|
      begin
        a = Annotation.new(annote)
        a.save!
        added += 1
      rescue
        errs += 1
      end
    end
    
    return {:added => added, :errs => errs}
  end
end
