# === COPYRIGHT:
#  Copyright (c) 2005-2010 North Carolina State University
#  Developed with funding for the National eXtension Initiative.
# === LICENSE:
#  BSD(-compatible)
#  see LICENSE file or view at http://about.extension.org/wiki/LICENSE

class Annotation < ActiveRecord::Base
  validates_length_of :url, :within => 1..1024
  validates_uniqueness_of :href
  
  has_many :annotation_events, :primary_key => :url
  
  after_save :log_add
  before_destroy :log_delete
  
  # href - id generated by google
  # url - URL string WITHOUT leading http://
  # added_at - date added by Google to CSE
  
  def added_at=(microseconds)
    write_attribute(:added_at, Time.at(microseconds/1000000))
  end
  
  def log_add
    self.log_event(AnnotationEvent::URL_ADDED)
  end
  
  def log_delete
    self.log_event(AnnotationEvent::URL_DELETED)
  end
 
  def log_event(action)
    AnnotationEvent.log_event(self, action)
  end
end
